# Generated by Django 3.2.7 on 2021-09-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('direction', models.CharField(choices=[('BACK-END', 'BACK-END'), ('GRAFIK DIZAYN', 'GRAFIK DIZAYN'), ('GRAFIK DIZAYN', 'GRAFIK DIZAYN'), ('FRON-TEND', 'FRON-TEND'), ('ROBOTOTEXNIKA VA MEXATRONIKA', 'ROBOTOTEXNIKA VA MEXATRONIKA')], max_length=100)),
                ('group_number', models.CharField(max_length=10)),
                ('course_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ("O'qituvchi", "O'qituvchi")], max_length=100)),
            ],
        ),
    ]
