# Generated by Django 3.2.7 on 2021-09-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitform',
            name='course_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unitform',
            name='direction',
            field=models.CharField(max_length=100),
        ),
    ]
