# Generated by Django 3.2.7 on 2021-09-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210907_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitform',
            name='time_managment',
            field=models.CharField(default='kiritilmadi', max_length=100),
        ),
    ]
