# Generated by Django 3.2.7 on 2021-09-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210908_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitform',
            name='course_number',
            field=models.CharField(choices=[('SELECTED', 'SELECTED'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ("O'qituvchi", "O'qituvchi")], max_length=100),
        ),
        migrations.AlterField(
            model_name='unitform',
            name='direction',
            field=models.CharField(choices=[('SELECTED', 'SELECTED'), ('BACK-END', 'BACK-END'), ('GRAFIK DIZAYN', 'GRAFIK DIZAYN'), ('GRAFIK DIZAYN', 'GRAFIK DIZAYN'), ('FRON-TEND', 'FRON-TEND'), ('ROBOTOTEXNIKA VA MEXATRONIKA', 'ROBOTOTEXNIKA VA MEXATRONIKA')], max_length=100),
        ),
    ]
