# Generated by Django 3.2.7 on 2021-09-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210908_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitform',
            name='time_managment',
        ),
        migrations.AlterField(
            model_name='unitform',
            name='direction',
            field=models.CharField(choices=[('KURSNI TANLANG', 'KURSNI TANLANG'), ('PYTHON dasturlash tili (back-end)', 'PYTHON dasturlash tili (back-end)'), ('GRAFIK DIZAYN', 'GRAFIK DIZAYN'), ('GRAFIK MODELLASHTIRISH', 'GRAFIK MODELLASHTIRISH'), ('JAVASCRIPT dasturlash tili (front-end)', 'JAVASCRIPT dasturlash tili (front-end)'), ('ROBOTOTEXNIKA VA MEXATRONIKA', 'ROBOTOTEXNIKA VA MEXATRONIKA'), ('SMM kursi (online marketing)', 'SMM kursi (online marketing)'), ('ANDROID mobil dasturlash', 'ANDROID mobil dasturlash')], max_length=100),
        ),
    ]
