# Generated by Django 3.2.7 on 2021-09-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210919_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitform',
            name='time_managment',
            field=models.CharField(choices=[('SIZGA QAYSI VAQT QULAY', 'SIZGA QAYSI VAQT QULAY'), ('ERTALAB (8-12)', 'ERTALAB (8-12)'), ('KECHKI (13-20)', 'KECHKI (13-20)')], max_length=100, null=True),
        ),
    ]
